### ISSUE TITLE
how to use LittleCASPaxos?

### ISSUE THREAD

**Issue by xiyusullos** [cschanck/single-file-java#21]
How could i use this LittleCASPaxos in my project? Is there any document?

**Comment by cschanck** [comment]
Hi Xi. 

First start here: https://github.com/cschanck/single-file-java/blob/master/src/docs/LittleCASPaxos.adoc

Then I would go here: https://github.com/cschanck/single-file-java/blob/master/src/test/java/org/sfj/LittleCASPaxosTest.java for example usage. In the test usage, there is a perfect in memory network impl, which just pushes messages around in memory. In reality you need to provide an actual network. Likewise you need to provide a durable storage class. 

Finally a Node impl is needed.

**Comment by xiyusullos** [comment]
Hi cschanck,

Thank you very much for your guide! Besides, I think it is very nice if the usage guides of all the single-file are listed in the readme file.
